// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024 EPAM Systems, Inc.

package com.github.istin.dmtools.common.kb.utils;

import com.github.istin.dmtools.common.kb.KBStatistics;
import com.github.istin.dmtools.common.kb.KBStructureBuilder;
import com.github.istin.dmtools.common.kb.model.AnalysisResult;
import com.github.istin.dmtools.common.kb.model.Answer;
import com.github.istin.dmtools.common.kb.model.KBResult;
import com.github.istin.dmtools.common.kb.model.Note;
import com.github.istin.dmtools.common.kb.model.PersonContributions;
import com.github.istin.dmtools.common.kb.model.Question;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Additional coverage tests for KBStructureManager focusing on paths not
 * exercised by the ID-mapping and merge regression tests:
 * - notes processing (file building, person stats, topic statistics)
 * - buildResult() with null analysis and with all entity types on disk
 * - merging caller-provided person contributions with contributions from files
 * - warning path when a person has stats but no contributions
 */
class KBStructureManagerCoverageTest {

    private static final Logger logger = LogManager.getLogger(KBStructureManagerCoverageTest.class);

    @TempDir
    Path tempDir;

    private KBStructureManager structureManager;

    @BeforeEach
    void setUp() {
        KBFileParser fileParser = new KBFileParser();
        KBStructureBuilder structureBuilder = new KBStructureBuilder();
        KBContextLoader contextLoader = new KBContextLoader(fileParser);
        PersonStatsCollector statsCollector = new PersonStatsCollector(fileParser, structureBuilder);
        KBStatistics statistics = new KBStatistics();
        structureManager = new KBStructureManager(structureBuilder, statsCollector, statistics, contextLoader);
    }

    /**
     * TEST: Notes are built with permanent IDs, counted in person profiles and topic statistics
     */
    @Test
    void testNotes_BuiltMappedAndCountedInProfileAndTopics() throws Exception {
        // GIVEN: Analysis with a note (temporary ID, as generated by AI)
        AnalysisResult analysis = new AnalysisResult();
        Note note = new Note();
        note.setId("n_1");  // Temporary ID
        note.setAuthor("Alice");
        note.setArea("ai");
        note.setTopics(Arrays.asList("machine-learning", "nlp"));
        note.setDate("2025-10-24T10:00:00Z");
        analysis.setQuestions(Arrays.asList());
        analysis.setAnswers(Arrays.asList());
        analysis.setNotes(Arrays.asList(note));

        // WHEN: Process
        structureManager.buildStructure(analysis, tempDir, "session_1", null, logger);

        // THEN: Note file should exist with permanent ID
        Path noteFile = tempDir.resolve("notes/n_0001.md");
        assertTrue(Files.exists(noteFile), "Note file should have permanent ID (n_0001.md)");

        // THEN: Person profile should reference the note with permanent ID
        Path profileFile = tempDir.resolve("people/Alice/Alice.md");
        assertTrue(Files.exists(profileFile), "Profile should exist");
        String profile = Files.readString(profileFile);
        assertTrue(profile.contains("[[../../notes/n_0001|n_0001]]"),
                "Profile should link note with permanent ID");
        assertTrue(profile.contains("notesContributed: 1"), "Frontmatter should show 1 note");

        // THEN: Topic files should reference the note (updateTopicWithStats targets a legacy
        // topics/<id>/<id>.md layout and no-ops on the flat layout, so assert on the flat file)
        Path topicFile = tempDir.resolve("topics/machine-learning.md");
        assertTrue(Files.exists(topicFile), "Topic file should exist");
        String topicContent = Files.readString(topicFile);
        assertTrue(topicContent.contains("n_0001"), "Topic file should reference the note");
    }

    /**
     * TEST: buildResult with null analysis result produces the fallback message
     */
    @Test
    void testBuildResult_NullAnalysisResult() throws Exception {
        // WHEN
        KBResult result = structureManager.buildResult(null, tempDir, new KBFileUtils());

        // THEN
        assertTrue(result.isSuccess(), "Result should be successful");
        assertEquals("KB processing completed.", result.getMessage());
        assertEquals(0, result.getQuestionsCount());
        assertEquals(0, result.getAnswersCount());
        assertEquals(0, result.getNotesCount());
        assertEquals(0, result.getPeopleCount());
        assertEquals(0, result.getTopicsCount());
        assertEquals(0, result.getAreasCount());
    }

    /**
     * TEST: buildResult counts all entity types on disk (and excludes -desc.md topic files)
     */
    @Test
    void testBuildResult_CountsAllEntityTypes() throws Exception {
        // GIVEN: KB structure on disk
        Files.createDirectories(tempDir.resolve("people/Alice"));
        Files.createDirectories(tempDir.resolve("people/Bob"));
        Files.createDirectories(tempDir.resolve("areas/ai"));
        Files.createDirectories(tempDir.resolve("topics"));
        Files.writeString(tempDir.resolve("topics/ml.md"), "x");
        Files.writeString(tempDir.resolve("topics/ml-desc.md"), "x");  // must be excluded
        Files.createDirectories(tempDir.resolve("questions"));
        Files.writeString(tempDir.resolve("questions/q_0001.md"), "x");
        Files.createDirectories(tempDir.resolve("answers"));
        Files.writeString(tempDir.resolve("answers/a_0001.md"), "x");
        Files.createDirectories(tempDir.resolve("notes"));
        Files.writeString(tempDir.resolve("notes/n_0001.md"), "x");

        // WHEN
        KBResult result = structureManager.buildResult(null, tempDir, new KBFileUtils());

        // THEN
        assertEquals(2, result.getPeopleCount());
        assertEquals(1, result.getTopicsCount(), "Description files must be excluded from topic count");
        assertEquals(1, result.getAreasCount());
        assertEquals(1, result.getQuestionsCount());
        assertEquals(1, result.getAnswersCount());
        assertEquals(1, result.getNotesCount());
    }

    /**
     * TEST: Caller-provided person contributions are merged with contributions collected
     * from files (new IDs added, existing IDs not duplicated, new people added),
     * and answer/note files on disk are counted into person stats.
     */
    @Test
    void testProvidedPersonContributions_MergedWithExistingFromFiles() throws Exception {
        // GIVEN: Session 1 - Alice asks a question (creates files and contributions on disk)
        AnalysisResult session1 = new AnalysisResult();
        Question q1 = new Question();
        q1.setId("q_1");
        q1.setAuthor("Alice");
        q1.setArea("ai");
        q1.setTopics(Arrays.asList("topic1"));
        q1.setDate("2025-10-24T10:00:00Z");
        session1.setQuestions(Arrays.asList(q1));
        session1.setAnswers(Arrays.asList());
        session1.setNotes(Arrays.asList());
        structureManager.buildStructure(session1, tempDir, "session_1", null, logger);

        // GIVEN: Session 2 - Bob asks a question, answers and writes a note
        AnalysisResult session2 = new AnalysisResult();
        Question q2 = new Question();
        q2.setId("q_1");  // temporary again, mapped to q_0002
        q2.setAuthor("Bob");
        q2.setArea("ai");
        q2.setTopics(Arrays.asList("topic2"));
        q2.setDate("2025-10-24T11:00:00Z");

        Answer a2 = new Answer();
        a2.setId("a_1");
        a2.setAuthor("Bob");
        a2.setArea("ai");
        a2.setTopics(Arrays.asList("topic2"));
        a2.setDate("2025-10-24T11:05:00Z");

        Note n2 = new Note();
        n2.setId("n_1");
        n2.setAuthor("Bob");
        n2.setArea("ai");
        n2.setTopics(Arrays.asList("topic2"));
        n2.setDate("2025-10-24T11:10:00Z");

        // Carol authors a note without an area: buildNoteFile skips it (no file on disk,
        // so no file-based contributions for her), but she is still counted as part of
        // the current analysis (non-null source when building her profile)
        Note carolNote = new Note();
        carolNote.setId("n_2");
        carolNote.setAuthor("Carol");
        carolNote.setArea(null);
        carolNote.setTopics(null);

        session2.setQuestions(Arrays.asList(q2));
        session2.setAnswers(Arrays.asList(a2));
        session2.setNotes(Arrays.asList(n2, carolNote));

        // GIVEN: Caller-provided contributions with extra items not present in files
        Map<String, PersonContributions> provided = new HashMap<>();

        // Alice already has q_0001 from files; provided contribution adds a new external ID
        PersonContributions aliceContribs = new PersonContributions();
        aliceContribs.getQuestions().add(
                new PersonContributions.ContributionItem("q_ext", "external", "2025-01-01"));
        provided.put("Alice", aliceContribs);

        // Bob gets external answer and note IDs merged in
        PersonContributions bobContribs = new PersonContributions();
        bobContribs.getAnswers().add(
                new PersonContributions.ContributionItem("a_ext", "external", "2025-01-02"));
        bobContribs.getNotes().add(
                new PersonContributions.ContributionItem("n_ext", "external", "2025-01-03"));
        provided.put("Bob", bobContribs);

        // Carol has no files at all - she must be added purely from provided contributions
        PersonContributions carolContribs = new PersonContributions();
        carolContribs.getQuestions().add(
                new PersonContributions.ContributionItem("q_carol", "external", "2025-01-04"));
        provided.put("Carol", carolContribs);

        // WHEN: Process session 2 with provided contributions
        structureManager.buildStructure(session2, tempDir, "session_2", provided, logger);

        // THEN: Alice keeps file-based question and gains the provided one
        String aliceProfile = Files.readString(tempDir.resolve("people/Alice/Alice.md"));
        assertTrue(aliceProfile.contains("q_0001"), "Alice should keep q_0001 from files");
        assertTrue(aliceProfile.contains("q_ext"), "Alice should gain provided q_ext");

        // THEN: Bob has file-based and provided contributions; answer/note files counted in stats
        String bobProfile = Files.readString(tempDir.resolve("people/Bob/Bob.md"));
        assertTrue(bobProfile.contains("q_0002"), "Bob should have mapped question q_0002");
        assertTrue(bobProfile.contains("a_0001"), "Bob should have answer a_0001 from files");
        assertTrue(bobProfile.contains("n_0001"), "Bob should have note n_0001 from files");
        assertTrue(bobProfile.contains("a_ext"), "Bob should gain provided a_ext");
        assertTrue(bobProfile.contains("n_ext"), "Bob should gain provided n_ext");
        assertTrue(bobProfile.contains("answersProvided: 1"), "Bob's answer file should be counted");
        assertTrue(bobProfile.contains("notesContributed: 1"), "Bob's note file should be counted");

        // THEN: Carol's profile is created solely from provided contributions
        Path carolProfile = tempDir.resolve("people/Carol/Carol.md");
        assertTrue(Files.exists(carolProfile), "Carol's profile should be created from provided contributions");
        assertTrue(Files.readString(carolProfile).contains("q_carol"),
                "Carol should have provided q_carol");
    }

    /**
     * TEST: Person present in the KB (people directory) but without any contributions
     * is still processed (warning path) and keeps the profile; also covers the
     * debug branch for people not part of the current analysis.
     */
    @Test
    void testPersonWithoutContributions_WarnPathAndStillProcessed() throws Exception {
        // GIVEN: An existing person directory with a profile but no Q/A/N files
        Path personDir = tempDir.resolve("people/Ivan_Tarasevich");
        Files.createDirectories(personDir);
        Files.writeString(personDir.resolve("Ivan_Tarasevich.md"),
                "---\nid: Ivan_Tarasevich\nname: Ivan Tarasevich\ntype: person\n"
                        + "sources:\n  - old_session\nquestionsAsked: 0\nanswersProvided: 0\nnotesContributed: 0\n"
                        + "---\n\n# Ivan Tarasevich\n");

        // GIVEN: Current analysis only involves Alice
        AnalysisResult analysis = new AnalysisResult();
        Question q = new Question();
        q.setId("q_1");
        q.setAuthor("Alice");
        q.setArea("ai");
        q.setTopics(Arrays.asList("topic1"));
        q.setDate("2025-10-24T10:00:00Z");
        analysis.setQuestions(Arrays.asList(q));
        analysis.setAnswers(Arrays.asList());
        analysis.setNotes(Arrays.asList());

        // GIVEN: Non-empty provided contributions so the merge path runs
        Map<String, PersonContributions> provided = new HashMap<>();
        PersonContributions aliceContribs = new PersonContributions();
        aliceContribs.getQuestions().add(
                new PersonContributions.ContributionItem("q_0001", "topic1", "2025-10-24T10:00:00Z"));
        provided.put("Alice", aliceContribs);

        // WHEN
        structureManager.buildStructure(analysis, tempDir, "session_2", provided, logger);

        // THEN: Ivan's profile still exists and Alice's profile was built
        assertTrue(Files.exists(personDir.resolve("Ivan_Tarasevich.md")),
                "Existing profile of person without contributions should remain");
        Path aliceProfile = tempDir.resolve("people/Alice/Alice.md");
        assertTrue(Files.exists(aliceProfile), "Alice's profile should be built");
        String aliceContent = Files.readString(aliceProfile);
        assertTrue(aliceContent.contains("q_0001"), "Alice should have her question");

        // THEN: Ivan was processed without a source added (not part of current analysis)
        String ivanContent = Files.readString(personDir.resolve("Ivan_Tarasevich.md"));
        assertFalse(ivanContent.contains("session_2"),
                "Person not in current analysis should not get the new source");
    }

    /**
     * TEST: buildStructure tolerates a null logger
     */
    @Test
    void testBuildStructure_NullLogger() throws Exception {
        // GIVEN
        AnalysisResult analysis = new AnalysisResult();
        Question q = new Question();
        q.setId("q_1");
        q.setAuthor("Alice");
        q.setArea("ai");
        q.setTopics(Arrays.asList("topic1"));
        q.setDate("2025-10-24T10:00:00Z");
        analysis.setQuestions(Arrays.asList(q));
        analysis.setAnswers(Collections.emptyList());
        analysis.setNotes(Collections.emptyList());

        // WHEN / THEN: no exception with null logger
        structureManager.buildStructure(analysis, tempDir, "session_1", null, null);
        assertTrue(Files.exists(tempDir.resolve("people/Alice/Alice.md")));
    }
}
