// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024 EPAM Systems, Inc.

package com.github.istin.dmtools.common.kb;

import com.github.istin.dmtools.common.kb.model.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Additional unit tests for KBStructureBuilder targeting previously uncovered branches:
 * early returns, incremental update paths, frontmatter fallback parsing,
 * topic aggregation from existing files, and the people index generation.
 */
class KBStructureBuilderCoverageTest {

    private KBStructureBuilder builder;

    @TempDir
    Path tempDir;

    @BeforeEach
    void setUp() {
        builder = new KBStructureBuilder();
    }

    // ------------------------------------------------------------------
    // Early returns for entities without area
    // ------------------------------------------------------------------

    @Test
    void testBuildQuestionFile_NoArea_Skipped() throws IOException {
        Question question = new Question();
        question.setId("q_0001");
        question.setAuthor("Alice");
        question.setArea(null);

        builder.buildQuestionFile(question, tempDir, "src", null);

        assertFalse(Files.exists(tempDir.resolve("questions")), "Questions dir should not be created");
    }

    @Test
    void testBuildQuestionFile_EmptyArea_Skipped() throws IOException {
        Question question = new Question();
        question.setId("q_0001");
        question.setAuthor("Alice");
        question.setArea("");

        builder.buildQuestionFile(question, tempDir, "src", null);

        assertFalse(Files.exists(tempDir.resolve("questions")), "Questions dir should not be created");
    }

    @Test
    void testBuildAnswerFile_NoArea_Skipped() throws IOException {
        Answer answer = new Answer();
        answer.setId("a_0001");
        answer.setAuthor("Bob");
        answer.setArea(null);

        builder.buildAnswerFile(answer, tempDir, "src");

        assertFalse(Files.exists(tempDir.resolve("answers")), "Answers dir should not be created");
    }

    @Test
    void testBuildNoteFile_NoArea_Skipped() throws IOException {
        Note note = new Note();
        note.setId("n_0001");
        note.setAuthor("Carol");
        note.setArea("");

        builder.buildNoteFile(note, tempDir, "src");

        assertFalse(Files.exists(tempDir.resolve("notes")), "Notes dir should not be created");
    }

    // ------------------------------------------------------------------
    // updateTopicWithStats
    // ------------------------------------------------------------------

    @Test
    void testUpdateTopicWithStats_MissingFile_NoOp() throws IOException {
        builder.updateTopicWithStats(tempDir, "no-such-topic", 1, 2, 3, Arrays.asList("alice"));

        assertFalse(Files.exists(tempDir.resolve("topics")), "Nothing should be created for missing topic");
    }

    @Test
    void testUpdateTopicWithStats_ReplacesAutoGeneratedSection() throws IOException {
        Path topicDir = tempDir.resolve("topics").resolve("docker");
        Files.createDirectories(topicDir);
        Path topicFile = topicDir.resolve("docker.md");
        Files.writeString(topicFile, "# Docker\n\n"
                + "<!-- AUTO_GENERATED_START -->\n"
                + "old stats\n"
                + "<!-- AUTO_GENERATED_END -->\n");

        builder.updateTopicWithStats(tempDir, "docker", 3, 2, 1, Arrays.asList("bob", "alice"));

        String content = Files.readString(topicFile);
        assertTrue(content.contains("- Questions: 3"), "Should contain questions count");
        assertTrue(content.contains("- Answers: 2"), "Should contain answers count");
        assertTrue(content.contains("- Notes: 1"), "Should contain notes count");
        assertTrue(content.contains("## Key Contributors"), "Should contain contributors section");
        // Contributors must be sorted alphabetically
        assertTrue(content.indexOf("[[alice|alice]]") < content.indexOf("[[bob|bob]]"),
                "Contributors should be sorted");
        assertFalse(content.contains("old stats"), "Old section should be replaced");
    }

    @Test
    void testUpdateTopicWithStats_NoContributors() throws IOException {
        Path topicDir = tempDir.resolve("topics").resolve("docker");
        Files.createDirectories(topicDir);
        Path topicFile = topicDir.resolve("docker.md");
        Files.writeString(topicFile, "<!-- AUTO_GENERATED_START -->\nx\n<!-- AUTO_GENERATED_END -->\n");

        builder.updateTopicWithStats(tempDir, "docker", 0, 0, 0, Collections.emptyList());

        String content = Files.readString(topicFile);
        assertTrue(content.contains("- Questions: 0"));
        assertFalse(content.contains("## Key Contributors"), "No contributors section for empty list");
    }

    // ------------------------------------------------------------------
    // Person profile update path (fallback frontmatter parsing)
    // ------------------------------------------------------------------

    @Test
    void testBuildPersonProfile_UpdateWithSingleSourceFrontmatter() throws IOException {
        Path personDir = tempDir.resolve("people").resolve("Bob_Smith");
        Files.createDirectories(personDir);
        Files.writeString(personDir.resolve("Bob_Smith.md"),
                "---\n"
                + "id: \"Bob_Smith\"\n"
                + "name: \"Bob Smith\"\n"
                + "type: \"person\"\n"
                + "sources: \"old_source\"\n"
                + "questionsAsked: 1\n"
                + "answersProvided: 0\n"
                + "notesContributed: 0\n"
                + "tags: [\"#person\", \"#source_old_source\"]\n"
                + "---\n\n"
                + "# Bob Smith\n\n"
                + "<!-- AUTO_GENERATED_START -->\n\n"
                + "old content\n\n"
                + "<!-- AUTO_GENERATED_END -->\n");

        builder.buildPersonProfile("Bob Smith", tempDir, "new_source", 5, 3, 2, null);

        String content = Files.readString(personDir.resolve("Bob_Smith.md"));
        assertTrue(content.contains("questionsAsked: 5"), "Should update questionsAsked");
        assertTrue(content.contains("answersProvided: 3"), "Should update answersProvided");
        assertTrue(content.contains("notesContributed: 2"), "Should update notesContributed");
        assertTrue(content.contains("\"old_source\""), "Should keep existing source");
        assertTrue(content.contains("\"new_source\""), "Should add new source");
        assertTrue(content.contains("- Questions asked: 5"), "Should use fallback counts section");
        assertFalse(content.contains("old content"), "Old auto-generated content should be replaced");
    }

    @Test
    void testBuildPersonProfile_UpdateWithMalformedIds() throws IOException {
        PersonContributions contributions = new PersonContributions();
        // null id -> extractIdNumber returns 0; non-numeric suffix -> NumberFormatException branch;
        // id without underscore -> parts.length != 2 branch
        contributions.getQuestions().add(new PersonContributions.ContributionItem(null, "t", "2024-01-01"));
        contributions.getQuestions().add(new PersonContributions.ContributionItem("q_abc", "t", "2024-01-02"));
        contributions.getQuestions().add(new PersonContributions.ContributionItem("plainid", "t", "2024-01-03"));
        contributions.getQuestions().add(new PersonContributions.ContributionItem("q_0005", "t", "2024-01-04"));

        builder.buildPersonProfile("Carol Jones", tempDir, "src", 4, 0, 0, contributions);

        Path personFile = tempDir.resolve("people/Carol_Jones/Carol_Jones.md");
        assertTrue(Files.exists(personFile), "Person file should be created");
        String content = Files.readString(personFile);
        assertTrue(content.contains("## Questions Asked"), "Should render questions section");
    }

    // ------------------------------------------------------------------
    // Area structure with existing files (incremental update)
    // ------------------------------------------------------------------

    @Test
    void testBuildAreaStructure_ReadsExistingAreaFileWithSingleContributor() throws IOException {
        // Existing area file with single-value contributors frontmatter and single-quoted title
        Path areaDir = tempDir.resolve("areas").resolve("dev");
        Files.createDirectories(areaDir);
        Files.writeString(areaDir.resolve("dev.md"),
                "---\n"
                + "type: area\n"
                + "title: 'Dev'\n"
                + "id: dev\n"
                + "sources: [\"old_source\"]\n"
                + "contributors: alice\n"
                + "created: \"2024-01-01T00:00:00Z\"\n"
                + "---\n\n"
                + "# Dev\n\n"
                + "## Topics\n\n"
                + "- [[docker|Docker]]\n\n"
                + "## Key Contributors\n\n");

        // A "broken" area whose .md is a directory -> read fails and is logged/skipped
        Files.createDirectories(tempDir.resolve("areas").resolve("broken").resolve("broken.md"));

        Question q = new Question();
        q.setId("q_0001");
        q.setAuthor("bob");
        q.setArea("Dev");
        q.setTopics(Arrays.asList("Kubernetes"));

        AnalysisResult analysis = new AnalysisResult();
        analysis.setQuestions(Arrays.asList(q));

        builder.buildAreaStructure(analysis, tempDir, "new_source");

        Path areaFile = areaDir.resolve("dev.md");
        String content = Files.readString(areaFile);
        assertTrue(content.contains("\"old_source\""), "Should keep existing source");
        assertTrue(content.contains("\"new_source\""), "Should add current source");
        assertTrue(content.contains("alice"), "Should keep existing contributor from frontmatter");
        assertTrue(content.contains("bob"), "Should add current contributor");
        assertTrue(content.contains("[[docker|Docker]]"), "Should keep topic from existing file");
        assertTrue(content.contains("[[kubernetes|Kubernetes]]"), "Should add new topic");
        assertTrue(content.contains("created: \"2024-01-01T00:00:00Z\""), "Should preserve created timestamp");
        // Broken area should not crash the build
        assertTrue(Files.isDirectory(tempDir.resolve("areas").resolve("broken")));
    }

    // ------------------------------------------------------------------
    // Question / Answer / Note files with all optional sections
    // ------------------------------------------------------------------

    @Test
    void testBuildQuestionFile_FullContent() throws IOException {
        Question question = new Question();
        question.setId("q_0001");
        question.setAuthor("Alice Brown");
        question.setText("How to cache layers?");
        question.setDate("2024-10-10");
        question.setArea("Dev");
        question.setTopics(Arrays.asList("Docker", "Caching"));
        question.setTags(Arrays.asList("buildkit"));
        question.setAnsweredBy("a_0001");
        Link link = new Link();
        link.setUrl("https://example.com");
        link.setTitle("Docs");
        question.setLinks(Arrays.asList(link));

        Answer answer = new Answer();
        answer.setId("a_0001");
        answer.setAnswersQuestion("q_0001");

        Note note = new Note();
        note.setId("n_0001");
        note.setAnswersQuestions(Arrays.asList("q_0001"));

        AnalysisResult analysis = new AnalysisResult();
        analysis.setAnswers(Arrays.asList(answer));
        analysis.setNotes(Arrays.asList(note));

        builder.buildQuestionFile(question, tempDir, "src", analysis);

        Path questionFile = tempDir.resolve("questions").resolve("q_0001.md");
        String content = Files.readString(questionFile);
        assertTrue(content.contains("answered: true"), "Should mark question as answered");
        assertTrue(content.contains("answeredBy: \"a_0001\""), "Should contain answeredBy");
        assertTrue(content.contains("\"buildkit\""), "Should contain LLM tags");
        assertTrue(content.contains("[Docs](https://example.com)"), "Should render links");
        assertTrue(content.contains("![[a_0001]]"), "Should embed referencing answer");
        assertTrue(content.contains("![[n_0001]]"), "Should embed referencing note");
        assertTrue(content.contains("[[dev|Dev]]"), "Should link area");
        assertTrue(content.contains("[[docker|Docker]], [[caching|Caching]]"), "Should link topics");
    }

    @Test
    void testBuildAnswerFile_FullContent() throws IOException {
        Answer answer = new Answer();
        answer.setId("a_0001");
        answer.setAuthor("Bob Smith");
        answer.setText("Use BuildKit cache mounts.");
        answer.setDate("2024-10-11");
        answer.setArea("Dev");
        answer.setTopics(Arrays.asList("Docker"));
        answer.setTags(Arrays.asList("caching"));
        answer.setAnswersQuestion("q_0001");
        answer.setQuality(0.85);
        Link link = new Link();
        link.setUrl("https://docs.example.com");
        link.setTitle("Reference");
        answer.setLinks(Arrays.asList(link));

        builder.buildAnswerFile(answer, tempDir, "src");

        Path answerFile = tempDir.resolve("answers").resolve("a_0001.md");
        String content = Files.readString(answerFile);
        assertTrue(content.contains("answersQuestion: \"q_0001\""), "Should contain answersQuestion");
        assertTrue(content.contains("\"caching\""), "Should contain LLM tags");
        assertTrue(content.contains("**Answers:** [[q_0001]]"), "Should link the answered question");
        assertTrue(content.contains("[Reference](https://docs.example.com)"), "Should render links");
        assertTrue(content.contains("**Quality Score:** 0.85"), "Should format quality score");
    }

    @Test
    void testBuildNoteFile_FullContent() throws IOException {
        Note note = new Note();
        note.setId("n_0001");
        note.setAuthor("Carol Jones");
        note.setText("Multi-stage builds reduce image size.");
        note.setDate("2024-10-12");
        note.setArea("Dev");
        note.setTopics(Arrays.asList("Docker", "Optimization"));
        note.setTags(Arrays.asList("multi-stage"));
        note.setAnswersQuestions(Arrays.asList("q_0001", "q_0002"));
        Link link = new Link();
        link.setUrl("https://blog.example.com");
        link.setTitle("Article");
        note.setLinks(Arrays.asList(link));

        builder.buildNoteFile(note, tempDir, "src");

        Path noteFile = tempDir.resolve("notes").resolve("n_0001.md");
        String content = Files.readString(noteFile);
        assertTrue(content.contains("answersQuestions: [\"q_0001\", \"q_0002\"]"), "Should contain answersQuestions");
        assertTrue(content.contains("\"multi-stage\""), "Should contain LLM tags");
        assertTrue(content.contains("**Answers Questions:** [[q_0001]], [[q_0002]]"), "Should link answered questions");
        assertTrue(content.contains("[Article](https://blog.example.com)"), "Should render links");
    }

    // ------------------------------------------------------------------
    // buildTopicFiles: aggregation from current analysis + existing files
    // ------------------------------------------------------------------

    @Test
    void testBuildTopicFiles_CollectsFromExistingFilesAndAnalysis() throws IOException {
        // Existing question file: answered, with a non-system tag
        Path questionsDir = tempDir.resolve("questions");
        Files.createDirectories(questionsDir);
        Files.writeString(questionsDir.resolve("q_0001.md"),
                "---\n"
                + "id: \"q_0001\"\n"
                + "author: \"alice\"\n"
                + "topics: [\"Docker\"]\n"
                + "answeredBy: \"a_0001\"\n"
                + "tags: [\"#question\", \"#source_x\", \"buildkit\"]\n"
                + "---\n\nbody\n");
        // Unreadable entry (directory with .md name) -> IOException is swallowed
        Files.createDirectories(questionsDir.resolve("unreadable.md"));

        // Existing answer linked to a question + standalone answer + answer only in files
        Path answersDir = tempDir.resolve("answers");
        Files.createDirectories(answersDir);
        Files.writeString(answersDir.resolve("a_0001.md"),
                "---\n"
                + "id: \"a_0001\"\n"
                + "author: \"bob\"\n"
                + "topics: [\"Docker\"]\n"
                + "answersQuestion: \"q_0001\"\n"
                + "tags: [\"#answer\", \"caching\"]\n"
                + "---\n\nbody\n");
        Files.writeString(answersDir.resolve("a_0003.md"),
                "---\n"
                + "id: \"a_0003\"\n"
                + "author: \"dave\"\n"
                + "topics: [\"Docker\"]\n"
                + "answersQuestion: \"q_0001\"\n"
                + "---\n\nbody\n");
        Files.createDirectories(answersDir.resolve("broken.md"));

        // Existing note with single-quoted id (quote-stripping branch)
        Path notesDir = tempDir.resolve("notes");
        Files.createDirectories(notesDir);
        Files.writeString(notesDir.resolve("n_0002.md"),
                "---\n"
                + "id: 'n_0002'\n"
                + "author: \"erin\"\n"
                + "topics: [\"Docker\"]\n"
                + "tags: [\"#note\"]\n"
                + "---\n\nbody\n");
        Files.createDirectories(notesDir.resolve("corrupt.md"));

        // Current analysis: q answered by a_0001, a_0002 standalone, n_0001 answers q_0001
        Question q = new Question();
        q.setId("q_0001");
        q.setAuthor("alice");
        q.setArea("Dev");
        q.setTopics(Arrays.asList("Docker"));
        q.setAnsweredBy("a_0001");
        q.setTags(Arrays.asList("buildkit"));

        Answer a1 = new Answer();
        a1.setId("a_0001");
        a1.setAuthor("bob");
        a1.setArea("Dev");
        a1.setTopics(Arrays.asList("Docker"));
        a1.setAnswersQuestion("q_0001");

        Answer a2 = new Answer();
        a2.setId("a_0002");
        a2.setAuthor("bob");
        a2.setArea("Dev");
        a2.setTopics(Arrays.asList("Docker"));

        Note n1 = new Note();
        n1.setId("n_0001");
        n1.setAuthor("carol");
        n1.setArea("Dev");
        n1.setTopics(Arrays.asList("Docker"));
        n1.setAnswersQuestions(Arrays.asList("q_0001"));

        // Note answering a question that is NOT in this topic -> stays standalone
        Note n3 = new Note();
        n3.setId("n_0003");
        n3.setAuthor("frank");
        n3.setArea("Dev");
        n3.setTopics(Arrays.asList("Docker"));
        n3.setAnswersQuestions(Arrays.asList("q_9999"));

        AnalysisResult analysis = new AnalysisResult();
        analysis.setQuestions(Arrays.asList(q));
        analysis.setAnswers(Arrays.asList(a1, a2));
        analysis.setNotes(Arrays.asList(n1, n3));

        builder.buildTopicFiles(analysis, tempDir, "src");

        Path topicFile = tempDir.resolve("topics").resolve("docker.md");
        assertTrue(Files.exists(topicFile), "Topic file should be created");
        String content = Files.readString(topicFile);

        // Aggregated non-system tags end up in frontmatter (sorted)
        assertTrue(content.contains("tags: [\"buildkit\", \"caching\"]"), "Should aggregate sorted tags");
        // q_0001 has both answer and note -> listed under Questions with Answers
        assertTrue(content.contains("## Questions with Answers"), "Should have Q&A section");
        assertTrue(content.contains("![[q_0001]]"), "Should embed answered question");
        // a_0001 (from analysis) and a_0003 (from existing files) both reference q_0001 -> excluded
        assertFalse(content.contains("![[a_0001]]"), "Linked answer should be excluded from standalone");
        assertFalse(content.contains("![[a_0003]]"), "File-only linked answer should be excluded from standalone");
        // a_0002 has no question reference -> standalone answer
        assertTrue(content.contains("## Additional Answers"), "Should have standalone answers section");
        assertTrue(content.contains("![[a_0002]]"), "Standalone answer should be embedded");
        // n_0001 answers q_0001 -> excluded from standalone notes;
        // n_0002 (from existing files) has no answersQuestions -> standalone note
        assertTrue(content.contains("## Notes"), "Should have standalone notes section");
        assertTrue(content.contains("![[n_0002]]"), "Standalone note from files should be embedded");
        assertFalse(content.contains("![[n_0001]]"), "Note answering a question should be excluded");
        // Description placeholder created
        assertTrue(Files.exists(tempDir.resolve("topics").resolve("docker-desc.md")),
                "Desc placeholder should be created");
    }

    @Test
    void testBuildTopicFiles_UnansweredQuestionSection() throws IOException {
        Question q = new Question();
        q.setId("q_0009");
        q.setAuthor("alice");
        q.setArea("Dev");
        q.setTopics(Arrays.asList("Kubernetes"));

        AnalysisResult analysis = new AnalysisResult();
        analysis.setQuestions(Arrays.asList(q));

        builder.buildTopicFiles(analysis, tempDir, "src");

        Path topicFile = tempDir.resolve("topics").resolve("kubernetes.md");
        String content = Files.readString(topicFile);
        assertTrue(content.contains("## Unanswered Questions"), "Should have unanswered questions section");
        assertTrue(content.contains("![[q_0009]]"), "Should embed unanswered question");
    }

    // ------------------------------------------------------------------
    // generatePeopleIndex
    // ------------------------------------------------------------------

    @Test
    void testGeneratePeopleIndex_NoPeopleDir_NoOp() throws IOException {
        builder.generatePeopleIndex(tempDir);

        assertFalse(Files.exists(tempDir.resolve("people")), "Nothing should be created");
    }

    @Test
    void testGeneratePeopleIndex_WithPeople() throws IOException {
        Files.createDirectories(tempDir.resolve("people").resolve("Bob_Smith"));
        Files.createDirectories(tempDir.resolve("people").resolve("Alice_Brown"));
        // Non-directory entry should be ignored
        Files.writeString(tempDir.resolve("people").resolve("stray.md"), "x");

        builder.generatePeopleIndex(tempDir);

        Path peopleFile = tempDir.resolve("people").resolve("people.md");
        assertTrue(Files.exists(peopleFile), "people.md should be created");
        String content = Files.readString(peopleFile);
        assertTrue(content.contains("**Total contributors:** 2"), "Should count only directories");
        assertTrue(content.contains("![[Alice_Brown/Alice_Brown]]"), "Should embed Alice profile");
        assertTrue(content.contains("![[Bob_Smith/Bob_Smith]]"), "Should embed Bob profile");
        assertTrue(content.indexOf("Alice_Brown") < content.indexOf("Bob_Smith"),
                "People should be sorted alphabetically");
        assertFalse(content.contains("stray"), "Files should be ignored");
        assertFalse(content.trim().endsWith("---"), "Trailing separator should be removed");
    }
}
