#!/usr/bin/env python3
"""Assemble index.html from template.html and the section partials.

Standard library only, no dependencies, no package manager. The built page is
committed, so serving the site still needs nothing but this directory — the
deploy workflow uploads it as it stands. This script is a convenience for
editing and a guard in CI, not a prerequisite for the page to work.

    python build.py            rebuild index.html
    python build.py --check    exit 1 if index.html is stale (used by CI)
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEMPLATE = ROOT / "template.html"
OUTPUT = ROOT / "index.html"

INCLUDE = re.compile(r"^([ \t]*)<!--\s*include:\s*(\S+?)\s*-->[ \t]*$", re.M)

BANNER = (
    "<!-- Generated by build.py from template.html and sections/. Do not edit:\n"
    "     run `python build.py` after changing a section. -->\n"
)


def render() -> str:
    if not TEMPLATE.exists():
        sys.exit(f"missing template: {TEMPLATE}")

    seen: list[str] = []

    def substitute(match: re.Match) -> str:
        indent, rel = match.group(1), match.group(2)
        part = (ROOT / rel).resolve()

        # Keep includes inside the landing directory: a path escaping it would
        # pull unrelated files into the published page.
        if not part.is_relative_to(ROOT):
            sys.exit(f"include escapes {ROOT}: {rel}")
        if not part.is_file():
            sys.exit(f"missing include: {rel}")

        seen.append(rel)
        body = part.read_text(encoding="utf-8").rstrip("\n")
        if indent:
            body = "\n".join(indent + line if line.strip() else line
                             for line in body.split("\n"))
        return body

    html = INCLUDE.sub(substitute, TEMPLATE.read_text(encoding="utf-8"))

    if "<!-- include:" in html:
        sys.exit("an include marker survived - check its spelling")

    # Every partial should be reachable, or a section has been orphaned.
    on_disk = {f"sections/{p.name}" for p in (ROOT / "sections").glob("*.html")}
    unused = sorted(on_disk - set(seen))
    if unused:
        sys.exit("sections not referenced by template.html: " + ", ".join(unused))

    lines = html.split("\n", 1)
    return lines[0] + "\n" + BANNER + lines[1]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify index.html matches the sources")
    args = parser.parse_args()

    built = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None

    if args.check:
        if built != current:
            sys.exit("index.html is out of date - run `python landing/build.py`")
        print(f"index.html is up to date ({len(built.splitlines())} lines)")
        return

    if built == current:
        print("index.html already up to date")
        return

    OUTPUT.write_text(built, encoding="utf-8", newline="\n")
    print(f"index.html rebuilt ({len(built.splitlines())} lines)")


if __name__ == "__main__":
    main()
