#!/usr/bin/env python3
"""Assemble index.html from template.html and the section partials.

Standard library only, no dependencies, no package manager. The built page is
committed, so serving the site still needs nothing but this directory — the
deploy workflow uploads it as it stands. This script is a convenience for
editing and a guard in CI, not a prerequisite for the page to work.

    python build.py            rebuild index.html
    python build.py --check    exit 1 if index.html is stale (used by CI)
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEMPLATE = ROOT / "template.html"
OUTPUT = ROOT / "index.html"
BUNDLE = ROOT / "styles" / "bundle.css"

INCLUDE = re.compile(r"^([ \t]*)<!--\s*include:\s*(\S+?)\s*-->[ \t]*$", re.M)

# Local stylesheets only — the Google Fonts link is also rel="stylesheet" and
# has to stay where it is.
SHEET = re.compile(r'^[ \t]*<link rel="stylesheet" href="(styles/[^"]+)">[ \t]*\n', re.M)

BANNER = (
    "<!-- Generated by build.py from template.html and sections/. Do not edit:\n"
    "     run `python build.py` after changing a section. -->\n"
)

BUNDLE_BANNER = (
    "/* Generated by build.py — do not edit.\n"
    "   Concatenated from the <link> tags in template.html, in that order:\n"
    "   the cascade depends on it, and a11y.css only wins by coming last. */\n"
)


def bundle_styles(html: str) -> tuple[str, str]:
    """Fold every local stylesheet into one file, in document order.

    Eighteen <link> tags are eighteen render-blocking requests for about 60 KB
    that never changes between them. Authoring stays split by concern; only the
    delivery is joined. Order comes from the template rather than a list kept
    here, so the two cannot disagree.
    """
    hrefs = SHEET.findall(html)
    if not hrefs:
        sys.exit("no local stylesheet links found in template.html")

    parts = [BUNDLE_BANNER]
    for href in hrefs:
        sheet = (ROOT / href).resolve()
        if not sheet.is_relative_to(ROOT):
            sys.exit(f"stylesheet escapes {ROOT}: {href}")
        if not sheet.is_file():
            sys.exit(f"missing stylesheet: {href}")
        parts.append(f"\n/* ===== {href} ===== */\n")
        parts.append(sheet.read_text(encoding="utf-8").rstrip("\n") + "\n")

    # Collapse the run of links into one, keeping the first tag's indentation.
    first = SHEET.search(html)
    indent = re.match(r"[ \t]*", first.group(0)).group(0)
    html = SHEET.sub("", html, count=len(hrefs))
    html = html[:first.start()] + f'{indent}<link rel="stylesheet" href="styles/bundle.css">\n' + html[first.start():]

    return html, "".join(parts)


def render() -> str:
    if not TEMPLATE.exists():
        sys.exit(f"missing template: {TEMPLATE}")

    seen: list[str] = []

    def substitute(match: re.Match) -> str:
        indent, rel = match.group(1), match.group(2)
        part = (ROOT / rel).resolve()

        # Keep includes inside the landing directory: a path escaping it would
        # pull unrelated files into the published page.
        if not part.is_relative_to(ROOT):
            sys.exit(f"include escapes {ROOT}: {rel}")
        if not part.is_file():
            sys.exit(f"missing include: {rel}")

        seen.append(rel)
        body = part.read_text(encoding="utf-8").rstrip("\n")
        if indent:
            body = "\n".join(indent + line if line.strip() else line
                             for line in body.split("\n"))
        return body

    html = INCLUDE.sub(substitute, TEMPLATE.read_text(encoding="utf-8"))

    if "<!-- include:" in html:
        sys.exit("an include marker survived - check its spelling")

    # Every partial should be reachable, or a section has been orphaned.
    on_disk = {f"sections/{p.name}" for p in (ROOT / "sections").glob("*.html")}
    unused = sorted(on_disk - set(seen))
    if unused:
        sys.exit("sections not referenced by template.html: " + ", ".join(unused))

    html, css = bundle_styles(html)

    lines = html.split("\n", 1)
    return lines[0] + "\n" + BANNER + lines[1], css


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify index.html and styles/bundle.css match the sources")
    args = parser.parse_args()

    built, css = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    current_css = BUNDLE.read_text(encoding="utf-8") if BUNDLE.exists() else None

    if args.check:
        stale = [name for name, new, old in
                 (("index.html", built, current), ("styles/bundle.css", css, current_css))
                 if new != old]
        if stale:
            sys.exit(f"{', '.join(stale)} out of date - run `python landing/build.py`")
        print(f"index.html ({len(built.splitlines())} lines) and "
              f"styles/bundle.css ({len(css.splitlines())} lines) are up to date")
        return

    if built == current and css == current_css:
        print("index.html and styles/bundle.css already up to date")
        return

    OUTPUT.write_text(built, encoding="utf-8", newline="\n")
    BUNDLE.write_text(css, encoding="utf-8", newline="\n")
    print(f"rebuilt index.html ({len(built.splitlines())} lines) and "
          f"styles/bundle.css ({len(css.splitlines())} lines)")


if __name__ == "__main__":
    main()
