// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024 EPAM Systems, Inc.

package com.github.istin.dmtools.index.mermaid;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Stream;

/**
 * Resolves Mermaid diagram snapshots generated by {@link MermaidIndex} for Jira tickets.
 * <p>
 * Expected directory layout mirrors the MermaidIndex output:
 * <pre>
 *   {storagePath}/{integration}/{projectKey}/{ticketKey}/{title}.mmd
 * </pre>
 * Only the main diagram file (directly inside the ticket-key folder) is considered;
 * attachment diagrams in subdirectories are ignored.
 */
public class MermaidSnapshotResolver {

    private static final Logger logger = LogManager.getLogger(MermaidSnapshotResolver.class);

    private final String storagePath;
    private final String integration;
    private final ConcurrentHashMap<String, Optional<String>> cache = new ConcurrentHashMap<>();

    public MermaidSnapshotResolver(String storagePath, String integration) {
        if (storagePath == null || storagePath.trim().isEmpty()) {
            throw new IllegalArgumentException("Storage path is required");
        }
        if (integration == null || integration.trim().isEmpty()) {
            throw new IllegalArgumentException("Integration is required");
        }
        this.storagePath = storagePath;
        this.integration = integration;
    }

    /**
     * Returns the Mermaid snapshot content for the given ticket key, if present.
     *
     * @param ticketKey ticket key in the form PROJECT-123
     * @return optional snapshot diagram text
     */
    public Optional<String> resolveSnapshot(String ticketKey) {
        if (ticketKey == null || ticketKey.trim().isEmpty()) {
            return Optional.empty();
        }
        return cache.computeIfAbsent(ticketKey, this::loadSnapshot);
    }

    private Optional<String> loadSnapshot(String ticketKey) {
        String projectKey = extractProjectKey(ticketKey);
        if (projectKey == null) {
            logger.debug("Cannot extract project key from ticket key: {}", ticketKey);
            return Optional.empty();
        }

        Path ticketDir = Paths.get(storagePath, integration, projectKey, ticketKey);
        if (!Files.isDirectory(ticketDir)) {
            logger.debug("No snapshot directory for ticket {}: {}", ticketKey, ticketDir);
            return Optional.empty();
        }

        try (Stream<Path> paths = Files.list(ticketDir)) {
            Optional<Path> snapshotPath = paths
                    .filter(Files::isRegularFile)
                    .filter(path -> path.toString().endsWith(".mmd"))
                    .max(Comparator.comparingLong(this::lastModifiedSafe));

            if (snapshotPath.isEmpty()) {
                logger.debug("No .mmd snapshot found for ticket {} in {}", ticketKey, ticketDir);
                return Optional.empty();
            }

            Path path = snapshotPath.get();
            String content = Files.readString(path, StandardCharsets.UTF_8);
            logger.debug("Loaded snapshot for ticket {} from {} ({} chars)", ticketKey, path, content.length());
            return Optional.of(content);
        } catch (IOException e) {
            logger.warn("Failed to read snapshot for ticket {}: {}", ticketKey, e.getMessage());
            return Optional.empty();
        }
    }

    private long lastModifiedSafe(Path path) {
        try {
            return Files.getLastModifiedTime(path).toMillis();
        } catch (IOException e) {
            return 0L;
        }
    }

    private String extractProjectKey(String ticketKey) {
        int dashIndex = ticketKey.indexOf('-');
        if (dashIndex > 0) {
            return ticketKey.substring(0, dashIndex);
        }
        return null;
    }
}
